per_page: "10"
users:
  ava_size: "100x100"
  default_avatar: "default.png"
books:
  per_page: 8
  book_size: "190x250"
  book_size_large: "300x400"
  default_book: "/assets/nhagiakim.jpg"

per_page: 4
